title: Tin Goyenda Org
email: tingoyendaorg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fahimscirex.github.io/tingoyenda/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tingoyendaorg
github_username: fahimscirex

theme: jekyll-theme-cayman
